# Generated by Django 4.0.3 on 2023-02-20 17:07

import adminpannel.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to=adminpannel.models.get_upload_path)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='pics')),
                ('name', models.CharField(max_length=100)),
                ('flavour', models.CharField(default='chocolate', max_length=100)),
                ('price', models.IntegerField()),
                ('shape', models.CharField(max_length=50)),
                ('size', models.IntegerField(default='6')),
                ('stock', models.CharField(choices=[('Stock Available', 'Stock Available'), ('Out of stock', 'Out of stock')], default='Stock Available', max_length=30)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpannel.categorys')),
            ],
        ),
    ]
