# Generated by Django 4.0.3 on 2023-03-11 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpannel', '0002_alter_categorys_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='price',
            new_name='original_price',
        ),
        migrations.AddField(
            model_name='products',
            name='final_price',
            field=models.IntegerField(default=0),
        ),
    ]
