# Generated by Django 4.0.3 on 2023-02-27 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminpannel', '0002_alter_categorys_img'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpannel.products')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0)),
                ('addedon', models.DateTimeField(default=django.utils.timezone.now)),
                ('upgrade', models.CharField(choices=[('1/2kg', '1/2kg'), ('1kg', '1kg')], default='1/2kg', max_length=10)),
                ('content', models.CharField(choices=[('egg', 'egg'), ('eggless', 'eggless')], default='egg', max_length=10)),
                ('message', models.CharField(default=None, max_length=40)),
                ('order_id', models.CharField(blank=True, max_length=200)),
                ('payment_id', models.CharField(default=None, max_length=200, null=True)),
                ('total_amount', models.FloatField(null=True)),
                ('payment_signature', models.CharField(default=None, max_length=200, null=True)),
                ('reciept_num', models.CharField(max_length=200, null=True)),
                ('delivery_address', models.CharField(blank=True, max_length=2000)),
                ('delivery_phone', models.CharField(blank=True, max_length=20)),
                ('date', models.CharField(default='', max_length=10)),
                ('pincode', models.IntegerField(default='000000', max_length=6)),
                ('payment_complete', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=1)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpannel.products')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=1)),
                ('addedon', models.DateTimeField(auto_now_add=True)),
                ('upgrade', models.CharField(choices=[('1/2kg', '1/2kg'), ('1kg', '1kg')], default='1/2kg', max_length=10)),
                ('content', models.CharField(choices=[('egg', 'egg'), ('eggless', 'eggless')], default='egg', max_length=10)),
                ('message', models.CharField(default=None, max_length=40)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpannel.products')),
            ],
        ),
    ]
