# Generated by Django 4.0.3 on 2023-02-28 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0002_remove_order_date_remove_order_delivery_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='product',
            new_name='product_name',
        ),
    ]
