# Generated by Django 4.0.3 on 2023-01-17 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0003_products_shape_products_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='flavour',
            field=models.CharField(default='chocolate', max_length=100),
        ),
        migrations.AlterField(
            model_name='products',
            name='shape',
            field=models.CharField(max_length=50),
        ),
    ]
