# Generated by Django 4.0.3 on 2023-02-28 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0003_rename_product_order_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Ordered', 'Ordered'), ('Processing', 'Processing'), ('Dispathched', 'Dispathched'), ('Delivered', 'Delivered')], default='In Progress', max_length=100),
        ),
    ]
