# Generated by Django 4.0.3 on 2023-01-18 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0004_products_flavour_alter_products_shape'),
    ]

    operations = [
        migrations.AddField(
            model_name='customercheckout',
            name='content',
            field=models.CharField(choices=[('egg', 'egg'), ('eggless', 'eggless')], default='egg', max_length=10),
        ),
        migrations.AddField(
            model_name='customercheckout',
            name='pincode',
            field=models.IntegerField(default='000000', max_length=6),
        ),
        migrations.AddField(
            model_name='customercheckout',
            name='upgrade',
            field=models.CharField(choices=[('1/2kg', '1/2kg'), ('1kg', '1kg')], default='1/2kg', max_length=10),
        ),
    ]
