# Generated by Django 4.0.3 on 2023-02-28 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0004_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Ordered', 'Ordered'), ('Processing', 'Processing'), ('Dispathched', 'Dispathched'), ('Delivered', 'Delivered')], default='Ordered', max_length=100),
        ),
    ]
