# Generated by Django 4.0.3 on 2023-03-11 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0006_customerreview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='price',
            new_name='final_price',
        ),
        migrations.AddField(
            model_name='order',
            name='orginal_price',
            field=models.IntegerField(default=0),
        ),
    ]
