# Generated by Django 4.0.3 on 2023-03-11 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0007_rename_price_order_final_price_order_orginal_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='final_price',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='orginal_price',
        ),
    ]
