# Generated by Django 4.0.3 on 2023-01-18 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0007_customercart_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customercart',
            name='message',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
