# Generated by Django 4.0.3 on 2023-01-18 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0009_remove_customercart_pincode_customercheckout_pincode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customercheckout',
            name='pincode',
        ),
        migrations.AddField(
            model_name='customercart',
            name='pincode',
            field=models.IntegerField(default='000000', max_length=6),
        ),
    ]
