# Generated by Django 4.0.3 on 2023-01-18 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0010_remove_customercheckout_pincode_customercart_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customercart',
            name='pincode',
            field=models.IntegerField(max_length=6),
        ),
    ]
