# Generated by Django 4.0.3 on 2023-01-18 13:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0012_alter_customercart_pincode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customercart',
            name='date',
        ),
        migrations.RemoveField(
            model_name='customercart',
            name='pincode',
        ),
        migrations.AddField(
            model_name='customercheckout',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='customercheckout',
            name='pincode',
            field=models.IntegerField(default='000000', max_length=6),
        ),
    ]
