# Generated by Django 4.0.3 on 2023-01-21 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0014_alter_customercart_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerpayedproducts',
            name='product_description',
        ),
    ]
