# Generated by Django 4.0.3 on 2023-01-24 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0019_alter_customercart_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customercart',
            name='message',
            field=models.CharField(default=None, max_length=40),
        ),
    ]
