# Generated by Django 4.0.3 on 2023-01-25 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0021_alter_customercart_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='customercart',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
