# Generated by Django 4.0.3 on 2023-01-27 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0022_customercart_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customercart',
            name='message',
        ),
    ]
