# Generated by Django 4.0.3 on 2023-01-28 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0024_customercart_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='customercart',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
