# Generated by Django 4.0.3 on 2023-01-30 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0025_customercart_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customercart',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
