# Generated by Django 4.0.3 on 2023-02-01 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0026_alter_customercart_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='customercart',
            name='p_qty',
            field=models.IntegerField(default=0),
        ),
    ]
