# Generated by Django 4.0.3 on 2023-02-02 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0027_customercart_p_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customercart',
            name='p_qty',
            field=models.IntegerField(default=1),
        ),
    ]
